### ISSUE TITLE
Retain tags if downloaded X times in the past X time periods

### ISSUE THREAD

**Issue by breymander** [nlowe/harbor-tag-retention-proposal#2]
I'd like to be able to retain image tags if they have been downloaded within the past X time periods.  This filter should take precedence over all other filters.

The use case for this is to leave any tags which could potentially be in use by either custom or one off processes.  For example, if a container image is created to help troubleshoot an issue, the tags may be in use for an extended period of time.  Under normal circumstances, this tag would be cleaned up due to being older than X time periods which could impact troubleshooting.

**Comment by nlowe** [comment]
I intend for users to be able to customize filter precedence (see my [my comment](https://github.com/nlowe/harbor-tag-retention-proposal/issues/3#issuecomment-419206466) on #3).

As for this specific rule I don't know if harbor tracks downloads in time buckets, I'm fairly certain it's just a simple counter. Would something like "Keep if last download was more recent than `x` days ago" work for this use case?

**Comment by breymander** [comment]
That should suffice.  #3 should cover any type of scenario where more complex filtering is required.
