### ISSUE TITLE
Customize order of filters and compose filters with logical expressions

### ISSUE THREAD

**Issue by breymander** [nlowe/harbor-tag-retention-proposal#3]
Allow users to customize the order of which filters are applied as well as the ability to chain them with AND or OR operators.

**Comment by nlowe** [comment]
I intended the order of filters to be changed, I'll make that clearer in the proposal.

Can you elaborate more on what you mean by AND/OR operators? Do you mean "Keep tag if `<x>` OR (`<y>` AND `<z>`)?

**Comment by breymander** [comment]
@nlowe That is exactly what I was suggesting.

**Comment by nlowe** [comment]
@breymander Do you envision this as always being a `keep` operation? Or would the inverse be useful as well? (i.e. "Delete tag if `<x>` OR (`<y>` AND `<z>`)")

**Comment by nlowe** [comment]
Also, can you give an example of an expression using these operators? I can't think of any that aren't already covered in one form or another by the existing proposal.

**Comment by nlowe** [comment]
As I've been thinking of this some more I'm not sure how this would be implemented. A DSL that we'd have to parse (almost like SQL)? An AST-builder in the web interface? There's a lot of hidden complexity here and I can't think of an example using expressions that couldn't be solved by the filter chain in the existing proposal.

**Comment by breymander** [comment]
After thinking about this, I am starting to agree with you.  All of my use cases were able to be accommodated by the proposal.
